package basicsOfException;

public class NestedTryBlock {

	public static void main(String[] args) {
		
		try {
			try {
				try {
					
				}
				catch(ArrayIndexOutOfBoundsException ai) {
					
				}
			}
			catch(ArithmeticException ae) {
				
			}
			
		}
		catch(Exception e) {
			
		}

	}

}
